# Generated by Django 5.1.3 on 2024-12-13 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, help_text='請選擇您的出生日期', null=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="電話號碼格式：'+886912345678'。", regex='^\\+?1?\\d{9,15}$')], verbose_name='電話號碼'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': '該用戶名已被使用。'}, help_text='必填。30個字符以內。只能包含字母、數字和@/./+/-/_', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', '用戶名只能包含字母、數字和 @/./+/-/_', 'invalid')], verbose_name='用戶名'),
        ),
    ]
