# Generated by Django 3.2.25 on 2024-03-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('radio', 'Single Choice'), ('checkbox', 'Multiple Choice')], default='radio', max_length=10),
        ),
    ]
