# Generated by Django 3.2.25 on 2024-03-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_question_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='position',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
