# Generated by Django 5.1.3 on 2024-12-13 14:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['id'], 'verbose_name': '選項', 'verbose_name_plural': '選項列表'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['position', 'pub_date'], 'verbose_name': '問題', 'verbose_name_plural': '問題列表'},
        ),
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否啟用'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(help_text='請輸入選項內容（最多200字）', max_length=200, verbose_name='選項內容'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polls.question', verbose_name='所屬問題'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='votes',
            field=models.IntegerField(default=0, verbose_name='票數'),
        ),
        migrations.AlterField(
            model_name='question',
            name='position',
            field=models.IntegerField(default=0, help_text='決定問題在問卷中的顯示順序', verbose_name='問題順序'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='發布時間'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(help_text='請輸入問題內容（最多200字）', max_length=200, verbose_name='問題內容'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('single', '單選題'), ('multiple', '多選題')], max_length=10, verbose_name='問題類型'),
        ),
    ]
